@startuml

package Post集約 <<Folder>> {
  class RootPost {
      string teamId
      string postId
      string[] tagIds
  }
  note bottom: 1つのpost紐づけられる\nタグは5つまで

  class Post {
      string id
      string content
  }
  note bottom: contentは300文字以内

  RootPost *-> Post
}

package Tag集約 <<Folder>> {
  class RootTag {
      string tagId
      string[] postIds
      string teamId
  }
  note bottom: 1つのタグにつけられる\npostの上限数が存在する

  class Tag {
      string id
      string content
  }
  note bottom: タグは最低1文字\nタグは最低100文字以内

  RootTag *-> Tag
}

package ClearkUser <<Folder>> {
    class ClearkUser {
        string id
        string teamId
    }
}

package SlackUser <<Folder>> {
    class SlackUser {
        string clearkUserId
    }
}

package GitHubUser <<Folder>> {
    class GitHubUser {
        string clearkUserId
    }
}

package Team <<Folder>> {
    class Team {
        string id
    }
}

package InvitationCode <<Folder>> {
    class InvitationCode {
        string teamId
    }
}

InvitationCode o-> Team
ClearkUser o-> Team
SlackUser o-> ClearkUser
GitHubUser o-> ClearkUser
RootPost o-> Team
RootTag o-> TEam
@enduml
